<?php

/**
 * We are inside My_View. For each of your views add this kind of header to keep your code clean and consistent.
 * Add type hinting comments (@method stdClass someMethod($someVar)) to enable code completion for helpers (PHPStorm) !
 *
 * @var $facebook Facebook
 * @var $this My_View
 */

?>

<h1>It works nice !</h1>
<p class="lead">
    We have an instance of Facebook !<br>
</p>

<pre><?=print_r($facebook, true)?></pre>

