<?php

/**
 * We are inside My_View. For each of your views add this kind of header to keep your code clean and consistent.
 * Add type hinting comments (@method stdClass someMethod($someVar)) to enable code completion for helpers (PHPStorm) !
 *
 * @var $facebook Facebook
 * @var $this My_View
 */

?>

<div class="page-header">
    <h2>How it works ?</h2>
</div>

<div class="jumbotron">
    <h1>Congratulations !</h1>
    <p>Your ultrafast boilerplate app is running ! NOW GET TO WORK !!!!111</p>
    <p>
        <a class="btn btn-lg btn-primary" href="https://github.com/jkobus/zend-for-facebook">View on GitHub &raquo;</a>
    </p>
</div>

<hr>

<h2>Testing facebook API</h2>
<p class="lead">
    We have an instance of Facebook !<br>
</p>

<pre><?=print_r($facebook, true)?></pre>

