<?php

/**
 * @var $this My_View
 */

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="<?=$this->baseUrl('assets/ico/favicon.png')?>">

    <title>Zend Framework Boilerplate application</title>
    <link href="<?=$this->baseUrl('assets/css/bootstrap.css')?>" rel="stylesheet">
    <link href="<?=$this->baseUrl('assets/css/main.css')?>" rel="stylesheet">
    <script src="<?=$this->baseUrl('assets/js/jquery.js')?>"></script>
    <script src="<?=$this->baseUrl('assets/js/bootstrap.js')?>"></script>
    <!--[if lt IE 9]>
    <script src="<?=$this->baseUrl('assets/js/html5shiv.js')?>"></script>
    <script src="<?=$this->baseUrl('assets/js/respond.min.js')?>"></script>
    <![endif]-->
</head>

<body>

<div class="container">

    <div class="navbar navbar-default">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?=$this->baseUrl()?>">Zend Framework 1 Boilerplate app</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?=$this->url(array('action' => 'facebook'))?>">Facebook Service Test</a></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="./">Default</a></li>
                <li><a href="#">Static top</a></li>
                <li><a href="#">Fixed top</a></li>
            </ul>
        </div>
    </div>

    <?=$this->layout()->content?>

    <hr>

    <div class="row">
        <div class="col-lg-12 text-center">
            &copy;2013
        </div>
    </div>

</div>


</body>
</html>
